services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.enrollment.enabled=true
      - ELASTIC_PASSWORD=monpassword
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: 'http://localhost:9200'
      # ELASTICSEARCH_USERNAME: "elastic"
      # ELASTICSEARCH_PASSWORD: "monpassword"
    networks:
      - elk
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:8.7.0
    ports:
      - "5044:5044"
    volumes:
      - ./logstash-config:/usr/share/logstash/pipeline
    networks:
      - elk
    depends_on:
      - elasticsearch

volumes:
  es_data:
networks:
  elk:
    driver: bridge